export { AboutSection } from './about-section';
export { EducationSection } from './education-section';
export { ExperienceSection } from './experience-section';
export { FloatingHeader } from './floating-header';
export { Footer } from './footer';
export { HeroSection } from './hero-section';
export { ProjectsSection } from './projects-section';
export { SkillsSection } from './skills-section';
export { TestimonialsSection } from './testimonials-section';
